//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int ID { get; set; }
        public string AccountNo { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
